# Generated by Django 2.1.7 on 2019-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('discription', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Earthquake_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('deaths', models.CharField(max_length=50)),
                ('magnitude', models.CharField(max_length=50)),
            ],
        ),
    ]
