# Generated by Django 2.1.7 on 2019-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_earthquake_earthquake_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Earthquake',
        ),
    ]
