# Generated by Django 2.1.7 on 2019-04-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190416_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temp',
            new_name='Temp_changes_couses',
        ),
    ]
