# Generated by Django 2.1.7 on 2019-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_imp_climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
