# Generated by Django 2.1.7 on 2019-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_city1'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
