# Generated by Django 2.1.7 on 2019-04-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_city_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='temperature',
        ),
    ]
