# Generated by Django 2.2.1 on 2019-05-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_remove_city_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city1',
            options={'verbose_name_plural': 'cities_1'},
        ),
    ]
